### PR TITLE
fix(community-organizations-policy): change replacement strategy

### PR DESCRIPTION
**Pull request by eduardomourar**
*Issue #, if available:* #68

*Description of changes:*

Fix error that happens when updating any of the target identifiers.

### CODE REVIEW

**Comment by zaro0508** [comment]
I have tested this fix by changing a combination of targetIds (OUs & accounts).  It seems to be working great.  thanks!

**Comment by OlafConijn** [comment]
uff, i completely missed this pr when i created https://github.com/org-formation/aws-resource-providers/pull/83
maybe take a moment offline/planning to see how we can progress with this together?

**Comment by eduardomourar** [comment]
> uff, i completely missed this pr when i created https://github.com/org-formation/aws-resource-providers/pull/83
> 
> maybe take a moment offline/planning to see how we can progress with this together?
> 
> 
Definitely. I am still trying to update to the newest version of the typescript library. I think now it works. Just needs further testing.

**Comment by eduardomourar** [comment]
There are a few changes needed in the dependencies that will take a little bit longer than I care to admit.

**Pull request merged**
