### PR TITLE
feat(security-hub): Master and Members type

### PR DESCRIPTION
**Pull request by OlafConijn**
*Issue #, if available:* #27

*Description of changes:*
imeplements Community::SecurityHub::Master & Community::SecurityHub::Members

### CODE REVIEW

**Comment by eduardomourar** [comment]
@OlafConijn, I believe the build is failing because package-lock is not up-to-date. My advise is to just delete it and run npm run i --save

**Comment by OlafConijn** [comment]
> @OlafConijn, I believe the build is failing because package-lock is not up-to-date. My advise is to just delete it and run npm run i --save

euh, i guess not?!

**Comment by eduardomourar** [comment]
There is a new version for both the RPDK as well as the common lib. Let me first test with another resource then we can try updating here

**Review by eduardomourar — APPROVED** [review]

**Comment by eduardomourar** [comment]
As discussed with Olaf, we need to implement the delete operation by copying the behavior of the following AWS CLI commands:

- get-enabled-standards
- batch-disable-standards
- disassociate-from-master-account
- disable-security-hub
- delete-members
- delete-invitations

**Pull request merged**
